services:
  private_keeper_V2:
    build:
      context: .
      dockerfile: Dockerfile
    image: private-keeper-v2-app
    container_name: private-keeper-v2-app
    restart: always
    environment:
      - DATABASE_URI=postgres://postgres:postgres@postgres_db:5432/privatekeeper?sslmode=disable
      - GRPC_SERVER=:3300
      - REDIS_URL=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - REDIS_TIMEOUT_SEC=2
      - TOKEN_NAME=token
      - TOKEN_EXP_HOURS=24
      - TOKEN_SECRET=secret
      - SERVER_CERT_FILE=/internal/tlsconfig/cert/server/server.crt
      - SERVER_KEY_FILE=/internal/tlsconfig/cert/server/server.key
      - SERVER_CA_FILE=/internal/tlsconfig/cert/server/ca.crt
    ports:
      - "3300:3300"
    depends_on:
      - redis
      - postgres_db

  # In-memory cache
  redis:
    image: redis:7-alpine3.20
    container_name: private-keeper-v2-redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=
      - REDIS_PORT=6379
      - REDIS_DATABASES=0
    volumes:
      - redis_data:/data

  # PostgreSQL database
  postgres_db:
    image: postgres:16-alpine3.20
    container_name: private-keeper-v2-postgres
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d privatekeeper" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=privatekeeper
    ports:
      - "5436:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  redis_data: